name: Build The Docker image and push it to the Docker Hub
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build the Docker image
              run: "docker build -t ${{ secrets.DOCKER_USERNAME }}/sp-to-mxm:${{ github.ref_name }} ."
            - name: Push the Docker image
              run: "docker push ${{ secrets.DOCKER_USERNAME }}/sp-to-mxm:${{ github.ref_name }}"